In [1]:
import numpy as np
#Создадим одномерный массив из списка
a1=np.array([1,3,5,7,9,11,13])
a1

array([ 1,  3,  5,  7,  9, 11, 13])

In [2]:
#Теперь создадим двумерный массив
a2=np.array([[1,3,5,7],[2,4,6,8]])
a2

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [3]:
#Создадим двумерный массив из нулей, размером 5 на 5
a3=np.zeros((5,5))
a3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
#Создадим двумерный массив из нулей, размером 2 на 4
a4=np.ones((2,4))
a4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
#Создадим массив состоящий из чётных числе в диапазоне от 2 до 14
a5=np.arange(2,15,2)
a5

array([ 2,  4,  6,  8, 10, 12, 14])

In [6]:
#Выведем атрибуты для массива a5
print("Форма массива:",a5.shape)
print("Тип массива:", a5.dtype)

Форма массива: (7,)
Тип массива: int64


In [7]:
#С помощью индексов получим элемент массива a2 на позции второй строки и 3 столбца
a2[1,2]

np.int64(6)

In [8]:
#С помощью срезов получим элементы массива a1 с пятого по шестой
a1[4:6]

array([ 9, 11])

In [9]:
#Поэлементно сложим массивы a1 и a5
a1+a5

array([ 3,  7, 11, 15, 19, 23, 27])

In [10]:
#Поэлементно умножаем массивы a1 и a5
a1*a5

array([  2,  12,  30,  56,  90, 132, 182])

In [11]:
#Вычисляем среднее значение элементов массива a2
np.mean(a2)

np.float64(4.5)